### ISSUE TITLE
delete command

### ISSUE THREAD

**Issue by bryanleejh** [CS2103JAN2017-F12-B4/main#12]
create a command for #11

**Comment by arishuynhvan** [comment]
@bryanleejh how is this different from #11 ?

**Comment by bryanleejh** [comment]
@arishuynhvan one is the user story one is the actual task. it was covered in tutorial.

**Comment by arishuynhvan** [comment]
@bryanleejh so we will need to keep both? When we make a pull request, how will you refer? Do we refer to both issues as well?

**Comment by bryanleejh** [comment]
@arishuynhvan @zhypaul @WangYu-g we just use the epic tag and leave the user story tags untouched for now. thanks for seeking clarification! (:
