### ISSUE TITLE
support CRUD for floating tasks

### ISSUE THREAD

**Issue by 4mirai** [CS2103JAN2017-F12-B4/main#31]

**Comment by arishuynhvan** [comment]
@WangYu-g does this include all the create, read, update, delete tasks as in issues #22 #21 #20 #11 ?

**Comment by 4mirai** [comment]
I guess so, but it is only for floating task (only description, no date or tag)

**Comment by arishuynhvan** [comment]
So I'll close those individual issues?

**Comment by 4mirai** [comment]
No hurry, I think those issues are for the task with date
