### ISSUE TITLE
Lots of new bugs

### ISSUE THREAD

**Issue by arishuynhvan** [CS2103JAN2017-F12-B4/main#51]
Hi @WangYu-g and @bryanleejh , sorry I was not working the past few days due to my health. When I return to our project, I've got numerous errors. Do you guys face the same errors with JUnit test too?

I'm on the master branch now

![image](https://cloud.githubusercontent.com/assets/7850717/24248851/0e8571a0-100c-11e7-99ae-11d20084bc61.png)

**Comment by bryanleejh** [comment]
@arishuynhvan @WangYu-g I got the same errors as well. Wang Yu says he has no problems when he runs the tests.

**Comment by 4mirai** [comment]
I don't know why I have no errors when i run tests locally. When I merged the pull request few days ago, it passed all the checks. But i just saw the latest merging commit failed the checks. I don't know why.

**Comment by 4mirai** [comment]
It is due to testfx update. Fixed.
