### ISSUE TITLE
Feedback for V0.3

### ISSUE THREAD

**Issue by okkhoy** [CS2103JAN2017-F12-B4/main#60]
## Admin stuff

- Contact us page
  - please provide your team's contact, not Prof. Damiths :-P
  - bug reports should direct to your project's issue tracker not addressbook level 4
- About us
  - @bryanleejh please update your mugshot to show your full face clearly :-)

-----

## User guide

- There are many references to address book in your user guide, please update and remove those references.
  - e.g. `Download latest version of addressbook.jar` <<< too bad!

- 2.2 Add
  - Add task to **address book**?? 
  - need to specify the format of the add command completely, there are no details given. 
    - how will the user know how to add a task without knowing what command to input?
    - need to add details on how to add all 3 types of tasks?

- 2.4 Edit
  - again, `edits an existing task in **address book**` <<< ?

- I am not reviewing the user guide further; please make it relevant to the product you are developing.
- Please note, you do not have much time before the documents become due in their final form.

-----

## Developer guide

- 2.1 Architecture
  - are you using the web component in your project? if so, please indicate how it is being used, if not, please update the diagram to reflect the same
  - the links to various files (like `MainApp` etc link back to `seedu\addressbook*` please update the links
  - please check the handouts on how to write sequence diagrams and correct the minor mistakes.
  - your sequence diagram still reads `deletePerson`; please update references to your project.

- errr... i realized that your design diagrams and relevant sections are not updated to reflect your project; hence, i am not reviewing it further.
- please also update the authors for each section; currently it reads cynthia, bernard etc., the ab-l4 developers.

@arishuynhvan @bryanleejh @WangYu-g @zhypaul  for your immediate action.
please take up this task on high priority and update your documents.

**Comment by arishuynhvan** [comment]
> Tip: The .pptx files used to create diagrams in this document can be found in the [diagrams](https://github.com/CS2103JAN2017-F12-B4/main/blob/master/docs/diagrams) folder. To update a diagram, modify the diagram in the pptx file, select the objects of the diagram, and choose Save as picture.

Images to be updated:

- [Events-Driven nature of the design](https://github.com/CS2103JAN2017-F12-B4/main/blob/master/docs/DeveloperGuide.md#events-driven-nature-of-the-design)

 ![SDforDeleteTask.png](https://github.com/CS2103JAN2017-F12-B4/main/blob/master/docs/images/SDforDeleteTask.png)
 
![SDforDeleteTaskEventHandling.png](https://github.com/CS2103JAN2017-F12-B4/main/blob/master/docs/images/SDforDeleteTaskEventHandling.png)

- [Logic Component](https://github.com/CS2103JAN2017-F12-B4/main/blob/master/docs/DeveloperGuide.md#23-logic-component)
  
![DeleteTaskSdForLogic.png](https://github.com/CS2103JAN2017-F12-B4/main/blob/master/docs/images/DeleteTaskSdForLogic.png)
